repos:
  # Ruff for linting and formatting (local hooks)
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff linting
        entry: uv run ruff check --fix
        language: system
        files: \.py$
        pass_filenames: true
      - id: ruff-format
        name: Ruff formatting
        entry: uv run ruff format
        language: system
        files: \.py$
        pass_filenames: true

  # Type checking with ty
  - repo: local
    hooks:
      - id: ty-check
        name: Type checking with ty
        entry: uv run ty check
        language: system
        files: \.py$
        pass_filenames: false

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
        exclude: ^docs/
      - id: check-toml
      - id: mixed-line-ending
